import { describe, it, expect } from "vitest";
import {
  buildCommentLine,
  buildGeneratorMeta,
  RANKRIOT_NAME,
  RANKRIOT_URL,
} from "./export-attribution";

describe("export attribution", () => {
  it("builds a #-prefixed comment line with generator, URL, project and date", () => {
    const line = buildCommentLine("Acme Co", "https://acme.com");
    expect(line.startsWith("# Generated by RankRiot")).toBe(true);
    expect(line).toContain(RANKRIOT_URL);
    expect(line).toContain("Project: Acme Co");
    expect(line).toContain("https://acme.com");
  });

  it("omits project fields when not provided", () => {
    const line = buildCommentLine();
    expect(line.startsWith("# Generated by RankRiot")).toBe(true);
    expect(line).not.toContain("Project:");
  });

  it("builds a machine-readable generator block for JSON", () => {
    const meta = buildGeneratorMeta("Acme Co", "https://acme.com", "pages");
    expect(meta.generator).toBe(RANKRIOT_NAME);
    expect(meta.generator_url).toBe(RANKRIOT_URL);
    expect(meta.project).toBe("Acme Co");
    expect(meta.project_url).toBe("https://acme.com");
    expect(meta.data_type).toBe("pages");
    // exported_at is an ISO timestamp
    expect(() => new Date(meta.exported_at).toISOString()).not.toThrow();
  });

  it("defaults to the canonical rankriot.app domain", () => {
    expect(RANKRIOT_URL).toContain("rankriot.app");
  });
});
