/**
 * Attribution embedded in every export so a file that travels — shared with a
 * client, fed into another SEO tool, published on the web — carries where it
 * came from. Format-appropriate: a comment line for CSV/text, a `generator`
 * block for JSON, a linked footer + <meta name="generator"> for HTML/PDF.
 */

export const RANKRIOT_NAME = "RankRiot";

/** Canonical public URL. Mirrors layout.tsx's metadataBase source of truth. */
export const RANKRIOT_URL =
  process.env.NEXT_PUBLIC_BASE_URL || "https://rankriot.app";

const today = (): string =>
  new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

/**
 * A single attribution line for CSV/plain-text exports, prefixed with `#` so
 * most tools treat it as a skippable comment. Contains the generator, its URL,
 * the project, and the date.
 */
export function buildCommentLine(
  projectName?: string,
  projectUrl?: string,
): string {
  const parts = [`# Generated by ${RANKRIOT_NAME} (${RANKRIOT_URL})`];
  if (projectName) parts.push(`Project: ${projectName}`);
  if (projectUrl) parts.push(projectUrl);
  parts.push(today());
  return parts.join(" — ");
}

export interface GeneratorMeta {
  generator: string;
  generator_url: string;
  exported_at: string;
  project?: string;
  project_url?: string;
  data_type?: string;
}

/** The machine-readable `generator` block embedded in JSON exports. */
export function buildGeneratorMeta(
  projectName?: string,
  projectUrl?: string,
  dataType?: string,
): GeneratorMeta {
  return {
    generator: RANKRIOT_NAME,
    generator_url: RANKRIOT_URL,
    exported_at: new Date().toISOString(),
    ...(projectName ? { project: projectName } : {}),
    ...(projectUrl ? { project_url: projectUrl } : {}),
    ...(dataType ? { data_type: dataType } : {}),
  };
}

/** Human-readable "Generated by RankRiot — <date>" string for report footers. */
export function buildFooterText(): string {
  return `Generated by ${RANKRIOT_NAME} (${RANKRIOT_URL}) — ${today()}`;
}
