import { ExportColumn, ExportableData } from "@/types/export";
import { PdfBranding } from "@/utils/pdf-report";
import { triggerDownload } from "@/utils/export";

const PRIMARY_COLOR = "#223971";
const ROW_ALT_COLOR = "#F5F5FA";

export function generateHtmlReport(
  data: ExportableData,
  columns: ExportColumn[],
  filename: string,
  branding?: PdfBranding,
  projectName?: string,
  projectUrl?: string,
): void {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const title = branding?.businessName
    ? `${branding.businessName} — SEO Report`
    : "SEO Report";

  const subtitleParts: string[] = [];
  if (branding?.clientName) subtitleParts.push(`Client: ${esc(branding.clientName)}`);
  if (projectName) subtitleParts.push(`Project: ${esc(projectName)}`);
  if (projectUrl) subtitleParts.push(esc(projectUrl));
  const subtitle = subtitleParts.join("  &bull;  ");

  const logoHtml = branding?.logoBase64
    ? `<img src="${branding.logoBase64}" alt="Logo" style="height:40px;margin-right:16px;vertical-align:middle;" />`
    : "";

  // Build table rows
  const headerCells = columns
    .map((col) => `<th>${esc(col.header)}</th>`)
    .join("");

  const bodyRows = data
    .map((row, i) => {
      const bgColor = i % 2 === 1 ? ` style="background:${ROW_ALT_COLOR}"` : "";
      const cells = columns
        .map((col) => {
          const value = row[col.key];
          const formatted = col.formatter ? col.formatter(value) : (value ?? "");
          return `<td>${esc(String(formatted))}</td>`;
        })
        .join("");
      return `<tr${bgColor}>${cells}</tr>`;
    })
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${esc(title)}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #333; background: #fff; }
  .header { background: ${PRIMARY_COLOR}; color: #fff; padding: 20px 32px; display: flex; align-items: center; justify-content: space-between; }
  .header-left { display: flex; align-items: center; }
  .header-title { font-size: 20px; font-weight: 700; }
  .header-subtitle { font-size: 13px; opacity: 0.85; margin-top: 4px; }
  .header-date { font-size: 13px; opacity: 0.85; text-align: right; }
  .table-wrapper { padding: 24px 32px; overflow-x: auto; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { background: ${PRIMARY_COLOR}; color: #fff; text-align: left; padding: 10px 12px; font-weight: 600; white-space: nowrap; }
  td { padding: 8px 12px; border-bottom: 1px solid #e5e5e5; word-break: break-word; max-width: 400px; }
  tr:hover td { background: #eef1f8; }
  .footer { padding: 16px 32px; text-align: center; color: #999; font-size: 12px; border-top: 1px solid #e5e5e5; margin-top: 16px; }

  @media print {
    .header { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    th { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    tr:hover td { background: transparent; }
    body { font-size: 11px; }
    .table-wrapper { padding: 12px; }
  }
</style>
</head>
<body>
  <div class="header">
    <div class="header-left">
      ${logoHtml}
      <div>
        <div class="header-title">${esc(title)}</div>
        ${subtitle ? `<div class="header-subtitle">${subtitle}</div>` : ""}
      </div>
    </div>
    <div class="header-date">${esc(dateStr)}</div>
  </div>

  <div class="table-wrapper">
    <table>
      <thead><tr>${headerCells}</tr></thead>
      <tbody>
${bodyRows}
      </tbody>
    </table>
  </div>

  <div class="footer">Generated by RankRiot &mdash; ${esc(dateStr)}</div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8;" });
  triggerDownload(blob, filename.endsWith(".html") ? filename : `${filename}.html`);
}

/** Escape HTML special characters */
function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
