import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { ExportColumn, ExportableData } from "@/types/export";

export interface PdfBranding {
  businessName?: string;
  clientName?: string;
  logoBase64?: string;
}

const PRIMARY_COLOR: [number, number, number] = [34, 57, 113]; // #223971
const ROW_ALT_COLOR: [number, number, number] = [245, 245, 250];

export function generatePdfReport(
  data: ExportableData,
  columns: ExportColumn[],
  filename: string,
  branding?: PdfBranding,
  projectName?: string,
  projectUrl?: string,
): void {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // --- Cover header ---
  // Color bar
  doc.setFillColor(...PRIMARY_COLOR);
  doc.rect(0, 0, pageWidth, 28, "F");

  let headerY = 10;
  let leftX = 14;

  // Logo
  if (branding?.logoBase64) {
    try {
      doc.addImage(branding.logoBase64, "PNG", leftX, 4, 20, 20);
      leftX = 38;
    } catch {
      // ignore bad image
    }
  }

  // Title text on color bar
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");

  const title = branding?.businessName
    ? `${branding.businessName} — SEO Report`
    : "SEO Report";
  doc.text(title, leftX, headerY + 2);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  const subtitleParts: string[] = [];
  if (branding?.clientName) subtitleParts.push(`Client: ${branding.clientName}`);
  if (projectName) subtitleParts.push(`Project: ${projectName}`);
  if (projectUrl) subtitleParts.push(projectUrl);

  if (subtitleParts.length > 0) {
    doc.text(subtitleParts.join("  •  "), leftX, headerY + 8);
  }

  // Date
  doc.setFontSize(9);
  doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), pageWidth - 14, headerY + 2, { align: "right" });

  // --- Data table ---
  const headers = columns.map((c) => c.header);
  const body = data.map((row) =>
    columns.map((col) => {
      const value = row[col.key];
      if (col.formatter) return col.formatter(value);
      if (value === null || value === undefined) return "";
      return String(value);
    }),
  );

  autoTable(doc, {
    startY: 34,
    head: [headers],
    body,
    styles: {
      fontSize: 8,
      cellPadding: 2,
      overflow: "linebreak",
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: PRIMARY_COLOR,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
    },
    alternateRowStyles: {
      fillColor: ROW_ALT_COLOR,
    },
    margin: { left: 10, right: 10 },
    didDrawPage: (hookData: any) => {
      // Footer on every page
      const pageCount = doc.getNumberOfPages();
      const currentPage = hookData.pageNumber || 1;
      doc.setFontSize(8);
      doc.setTextColor(140, 140, 140);
      doc.text(
        `Page ${currentPage} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 8,
        { align: "center" },
      );
      doc.text(
        "Generated by RankRiot",
        pageWidth - 10,
        doc.internal.pageSize.getHeight() - 8,
        { align: "right" },
      );
    },
  });

  // Fix page count on all pages (since didDrawPage fires before total is known)
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 140);
    // Overwrite page number area
    const footerY = doc.internal.pageSize.getHeight() - 8;
    doc.setFillColor(255, 255, 255);
    doc.rect(0, footerY - 4, pageWidth / 2 + 20, 8, "F");
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, footerY, {
      align: "center",
    });
  }

  doc.save(filename.endsWith(".pdf") ? filename : `${filename}.pdf`);
}
